### ISSUE TITLE
Client ID - dummies guide?

### ISSUE THREAD

**Issue by TharuMCD** [magaHH/homebridge-bmw-connected-accessories#1]
Many thanks for sharing this code.  For a novice like me, any chance of giving an explanation on how to find one's personal Client ID?

Kind regards, Michael.

**Comment by magaHH** [comment]
Google is your friend ;)

https://letmegooglethat.com/?q=dbf0a542%2Bbmw%2Bclient%2Bid

**Comment by TharuMCD** [comment]
Many thanks – will give it a go.  Kind regards, Michael.

From: magaHH ***@***.***>
Reply to: magaHH/homebridge-bmw-connected-accessories ***@***.***>
Date: Wednesday, 7 April 2021 at 14:51
To: magaHH/homebridge-bmw-connected-accessories ***@***.***>
Cc: Michael David ***@***.***>, Author ***@***.***>
Subject: Re: [magaHH/homebridge-bmw-connected-accessories] Client ID - dummies guide? (#1)


Google is your friend ;)

https://letmegooglethat.com/?q=dbf0a542%2Bbmw%2Bclient%2Bid<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fletmegooglethat.com%2F%3Fq%3Ddbf0a542%252Bbmw%252Bclient%252Bid&data=04%7C01%7C%7C24b507f83fbb41d9377a08d8f9cc454b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637534003023040084%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kmHJqaUhtBzf7KVTvOjOhkiW970ZZ%2B8hX8l%2FlrIuiN4%3D&reserved=0>
